# filter for codelists for which no values (and hence codelists) are given
#
# Variables
# {concept}     ... the concept for the the filtered column
# {codelists}   ... the codelists, that are possible here
# {separator}   ... separator character for list of matching enum values
{
  # bind codelists
  VALUES ?inputCodelist { {codelists} }
  
  # find matching columns
  ?colDesc  qb:concept/skos:exactMatch {concept} ;
            qb:codeList                ?inputCodelist
}